name: iOS Release

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      # Créer le fichier .env à partir des secrets
      - name: Create .env file
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env
          echo "SUPABASE_LOGIN_PASSWORD=${{ secrets.SUPABASE_LOGIN_PASSWORD }}" >> .env
          echo "SENDINBLUE_API_KEY=${{ secrets.SENDINBLUE_API_KEY }}" >> .env

      - name: Install Flutter dependencies
        run: |
          flutter pub get

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod repo update

      - name: Import Signing Certificate
        env:
          CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE }}
          P12_PASSWORD: "12345"
          KEYCHAIN_PASSWORD: "temporary_keychain_password"
        run: |
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -t 3600 -l build.keychain

          echo $CERTIFICATE_BASE64 | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
          rm certificate.p12

      - name: Import Provisioning Profile
        env:
          PROVISIONING_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE }}
        run: |
          echo $PROVISIONING_PROFILE_BASE64 | base64 --decode > provisioning.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp provisioning.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          rm provisioning.mobileprovision

      - name: Clean and update dependencies
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          pod cache clean --all
          pod repo update
          pod install --repo-update --verbose

      - name: Configure Xcode project
        run: |
          cd ios
          ruby -e '
            require "xcodeproj"
            project_path = "Runner.xcodeproj"
            project = Xcodeproj::Project.open(project_path)
            project.targets.each do |target|
              if target.name == "Runner"
                target.build_configurations.each do |config|
                  config.build_settings["CODE_SIGN_STYLE"] = "Manual"
                  config.build_settings["DEVELOPMENT_TEAM"] = "94VW99RYDQ"
                  config.build_settings["PROVISIONING_PROFILE_SPECIFIER"] = "Al Mahir Profile"
                  config.build_settings["CODE_SIGN_IDENTITY"] = "iPhone Distribution: Hamath Moussa Kane (94VW99RYDQ)"
                end
              end
            end
            project.save
          '

      - name: Disable code signing for third-party frameworks
        run: |
          cd ios
          find Pods -name "*.xcconfig" -exec sed -i '' 's/CODE_SIGN_IDENTITY = "iPhone Developer";/CODE_SIGN_IDENTITY = "";/g' {} +
          find Pods -name "*.xcconfig" -exec sed -i '' 's/CODE_SIGNING_REQUIRED = YES;/CODE_SIGNING_REQUIRED = NO;/g' {} +
          find Pods -name "*.xcconfig" -exec sed -i '' 's/CODE_SIGNING_ALLOWED = YES;/CODE_SIGNING_ALLOWED = NO;/g' {} +

      - name: Clean Derived Data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Build iOS app
        env:
          DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
        run: |
          flutter build ios --release --no-codesign \
            --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            --dart-define=SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} \
            --dart-define=SUPABASE_LOGIN_PASSWORD=${{ secrets.SUPABASE_LOGIN_PASSWORD }} \
            --dart-define=SENDINBLUE_API_KEY=${{ secrets.SENDINBLUE_API_KEY }}
          cd ios
          xcodebuild clean -workspace Runner.xcworkspace -scheme Runner -destination "generic/platform=iOS"
          xcodebuild archive -workspace Runner.xcworkspace -scheme Runner -configuration Release \
            -destination "generic/platform=iOS" -sdk iphoneos -archivePath "build/Runner.xcarchive" \
            -allowProvisioningUpdates -allowProvisioningDeviceRegistration \
            DEVELOPMENT_TEAM="94VW99RYDQ" \
            PROVISIONING_PROFILE_SPECIFIER="Al Mahir Profile" \
            CODE_SIGN_IDENTITY="iPhone Distribution: Hamath Moussa Kane (94VW99RYDQ)" \
            CODE_SIGN_STYLE=Manual \
            ENABLE_BITCODE=NO \
            DEBUG_INFORMATION_FORMAT="dwarf-with-dsym" \
            ARCHS="arm64" \
            ONLY_ACTIVE_ARCH=NO \
            archive CODE_SIGNING_ALLOWED=NO

      - name: Export IPA
        env:
          DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
        run: |
          export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
          cd ios
          xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build -allowProvisioningUpdates

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ios-build
          path: |
            ios/build/**/*.ipa
            ios/build/Runner.xcarchive
          retention-days: 5

      - name: Upload to App Store Connect
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        run: |
          cd ios
          mkdir -p ~/.appstoreconnect/private_keys
          echo "$APP_STORE_CONNECT_API_KEY" > ~/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_KEY_ID.p8
          IPA_PATH=$(find . -name "*.ipa" -type f | head -n 1)
          xcrun altool --output-format xml --upload-app --file "$IPA_PATH" --type ios \
            --apiKey "$APP_STORE_CONNECT_KEY_ID" \
            --apiIssuer "$APP_STORE_CONNECT_ISSUER_ID"
          rm -f ~/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_KEY_ID.p8
